- name: Install Docker on Debian-based systems
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: ansible_os_family | default('Unknown') == "Debian"

- name: Install Docker on macOS
  homebrew:
    name: docker
    state: present
  when: ansible_os_family | default('Unknown') == "Darwin"
