# name: Backend CI/CD

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - "backend/**"

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: 1.21

#       - name: Build Backend
#         run: |
#           cd backend
#           go build -o app
