apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config

---
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  selector:
    app: caddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    {
        email fullstackfusions@gmail.com
    }

    localhost:80 {  # Explicitly force HTTP only
        reverse_proxy /greet backend-service:8080  # Use Kubernetes service name
        reverse_proxy /* frontend-service:80 {     # Use Kubernetes service name
            header_up Host {host}
        }
    }
