apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-todo
  template:
    metadata:
      labels:
        app: fastapi-todo
    spec:
      containers:
        - name: fastapi-todo
          image: fastapi-todo-app:latest
          ports:
            - containerPort: 8000
        - name: streamlit-todo
          image: streamlit-todo-app:latest
          ports:
            - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: fastapi-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
