- name: Build Docker Image
  hosts: localhost
  tasks:
    - name: Build Docker Image
      community.docker.docker_image:
        name: go-app
        build:
          path: "/Users/mihirzz/Codes/mihirzzsolutions/MyProjects/PlayTime/DevOpsDevelopmentProjects/ansible_docker_automation/roles/app_deploy/files"
        source: build
      environment:
        DOCKER_HOST: "unix:///var/run/docker.sock"
